### ISSUE TITLE
Cambiar Coloreado de las Islas Argentinas 

### ISSUE THREAD

**Issue by anthieni** [anthieni/gis-book#1]
Cambiar el grafico de las Islas Argentinas ubicado en gis-book/convert/convert_es/img/Seleccion_rectangulo.png para posterior generación del pdf

**Comment by anthieni** [comment]
@malenalibman Avisa cuando tengas disponible la imagen, vamos a usar un brach diferentes al master para la modificación

**Comment by malenalibman** [comment]
![imagen1](https://user-images.githubusercontent.com/5738872/31194843-be191832-a91e-11e7-9605-a54e624bdfd6.png)

**Comment by malenalibman** [comment]
se subió la nueva imagen y se reemplazó
https://github.com/elcoloo/gis-book/commit/c9fc2767416b8759580d1390a6f24fd958b7b4c3
